project:
  type: website
  output-dir: docs 

website:
  title: "Breakthrough BI"
  navbar:
    logo: breakthroughbi_logo.jpeg
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: how_brands_grow.qmd
        text: How Brands Grow
      - href: NBD_Dirichlet.qmd
        text: NBD Dirichlet model
      - href: workbooks.qmd
        text: Workbooks

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link-external-newwindow: true
    md_extensions: +link_attributes

editor: visual

